import CopyButton from "./CopyButton";
import EmailComposer from "./EmailComposer";
import { freshAndroidDirectPosts, freshAndroidEmailApplications, freshFlutterDirectPosts, freshFlutterEmailApplications } from "./fresh-data";

const flutterJobs = [
  { company: "Delta Retail Solution", role: "Flutter Mobile Developer", location: "القاهرة، مصر", mode: "دوام كامل · Hybrid", age: "LinkedIn مفتوح · منشور منذ 5 أيام · تحققت 5 أكتوبر", salary: "مخفي", match: "تطابق قوي", matchClass: "strong", why: "2+ سنوات Flutter/Dart، Android وiOS، REST/JSON، state management، الأمان، النشر، وoffline sync؛ تطابق مباشر مع خبرة محمد.", note: "الدور مرتبط بتطبيقات retail/ERP وbarcode؛ تاريخ الإغلاق المعلن 5 نوفمبر 2026.", href: "https://eg.linkedin.com/jobs/view/flutter-mobile-developer-at-delta-retail-solution-4473554200", coverLetter: `Dear Delta Retail Solution Hiring Team,\n\nI am applying for the Flutter Mobile Developer position in Cairo. I have more than three years of production experience building Flutter applications for Android, iOS, and Windows using Dart, BLoC/Cubit, GetX, Clean Architecture, REST APIs, Firebase, Hive, SQLite, testing, GitHub Actions, and Fastlane.\n\nMy experience with cross-platform delivery, secure API integrations, local persistence, performance optimization, testing, and production releases aligns closely with Delta Retail Solution’s Flutter, Dart, Android/iOS, REST, and offline-synchronization requirements.\n\nPortfolio: https://muhamaadessam.github.io/\n\nBest regards,\nMuhammad Essam` },
  { company: "AppFactory", role: "Flutter Developer", location: "نيو كايرو، مصر", mode: "دوام كامل · On-site", age: "صفحة الشركة الرسمية مفتوحة · تحققت 5 أكتوبر", salary: "تنافسي حسب الخبرة", match: "تطابق قوي", matchClass: "strong", why: "3–5 سنوات Flutter إنتاجي، Dart، state management، REST/WebSockets، الاختبارات وCI/CD؛ تطابق مباشر مع خبرة محمد.", note: "On-site في New Cairo؛ الراتب تنافسي وغير محدد رقميًا، والتقديم من زر Start Application.", href: "https://www.appfactoryltd.com/flutter-developer.html", coverLetter: `Dear AppFactory Hiring Team,\n\nI am applying for the Flutter Developer position in New Cairo. I have more than three years of production experience building Flutter applications for Android, iOS, and Windows using Dart, BLoC/Cubit, GetX, Clean Architecture, REST APIs, Firebase, Hive, SQLite, testing, GitHub Actions, and Fastlane.\n\nMy experience with production feature ownership, responsive UI, API and real-time integrations, performance improvements, automated tests, and mobile release workflows aligns closely with AppFactory’s Flutter, Dart, state management, REST/WebSockets, testing, and CI/CD requirements.\n\nPortfolio: https://muhamaadessam.github.io/\n\nBest regards,\nMuhammad Essam` },
  { company: "Div Systems", role: "Flutter Mobile Application Developer", location: "القاهرة، مصر", mode: "دوام كامل · On-site", age: "صفحة الشركة الرسمية تعرض Apply Now · تحققت 5 أكتوبر", salary: "مخفي", match: "تطابق قوي", matchClass: "strong", why: "3+ سنوات Flutter/Dart، OOP/design patterns، Git وREST؛ صفحة الشركة ما زالت تعرض Apply Now في القاهرة.", note: "القاهرة؛ الراتب غير معلن ومسار التقديم مباشر من صفحة الوظيفة.", href: "https://portal.div-systems.com/jobs/detail/flutter-mobile-application-developer-33", coverLetter: `Dear Div Systems Hiring Team,\n\nI am applying for the Flutter Mobile Application Developer position in Cairo. I have more than three years of production experience building Flutter applications for Android, iOS, and Windows using Dart, BLoC/Cubit, GetX, Clean Architecture, REST APIs, Firebase, Hive, SQLite, testing, GitHub Actions, and Fastlane.\n\nMy background in mobile architecture, API integration, testing, performance improvements, and release workflows matches the role’s Flutter, Dart, design-pattern, Git, and REST requirements.\n\nPortfolio: https://muhamaadessam.github.io/\n\nBest regards,\nMuhammad Essam` },
  { company: "ArpuPlus / ARPU Telecommunications Services", role: "Mid-Level Flutter Developer", location: "القاهرة، مصر", mode: "دوام كامل · نموذج العمل غير معلن", age: "Dr.Job يعرض Apply ومسارًا مفتوحًا · تحققت 5 أكتوبر", salary: "مخفي", match: "تطابق قوي", matchClass: "strong", why: "2+ سنوات Flutter/Dart وBLoC وREST وGit وبناء تطبيقات Android/iOS وFlutter Web؛ قريب جدًا من خبرة محمد.", note: "التقديم عبر Dr.Job ويتطلب تسجيلًا أو دخولًا؛ الصفحة تعرض موعدًا نهائيًا 10 ديسمبر 2026.", href: "https://www.drjobpro.com/egypt/jobs/flutter-developer-cairo-arpu-telecommunication-services-MTXLDXXH27AIUN9", coverLetter: `Dear ArpuPlus Hiring Team,\n\nI am applying for the Mid-Level Flutter Developer position in Cairo. I have more than three years of production experience building Flutter applications for Android, iOS, and Windows using Dart, BLoC/Cubit, GetX, Clean Architecture, REST APIs, Firebase, Hive, SQLite, testing, GitHub Actions, and Fastlane.\n\nMy experience with cross-platform mobile delivery, scalable architecture, state management, API integration, performance optimization, testing, and release workflows aligns closely with ArpuPlus’s Flutter, Dart, BLoC, REST, Git, and Android/iOS requirements.\n\nPortfolio: https://muhamaadessam.github.io/\n\nBest regards,\nMuhammad Essam` },
  { company: "Adree", role: "Flutter Developer", location: "القاهرة، مصر", mode: "دوام كامل · النموذج غير معلن", age: "Workable يعرض صفحة الوظيفة · تحققت 5 أكتوبر · منشور LinkedIn منذ شهرين", salary: "مخفي", match: "فرصة ممكنة", matchClass: "stretch", why: "3–6 سنوات Flutter وDart وBLoC/Provider/Riverpod/GetX وREST/GraphQL وFirebase؛ الملاءمة قوية لكن الإعلان أقدم من بقية القائمة.", note: "قدّميها بعد الأدوار الأحدث؛ الراتب ونموذج العمل غير معلنين.", href: "https://apply.workable.com/adree/j/089D2DAF05/", coverLetter: `Dear Adree Hiring Team,\n\nI am applying for the Flutter Developer position in Cairo. I have more than three years of production experience building Flutter applications for Android, iOS, and Windows using Dart, BLoC/Cubit, GetX, Clean Architecture, REST APIs, Firebase, Hive, SQLite, testing, GitHub Actions, and Fastlane.\n\nMy experience with modular architecture, API integrations, local persistence, performance improvements, debugging, and automated mobile releases aligns closely with Adree’s Flutter, state-management, Firebase, storage, testing, and CI/CD requirements.\n\nPortfolio: https://muhamaadessam.github.io/\n\nBest regards,\nMuhammad Essam` },
] as const;

const androidJobs = [
  { company: "Delta Retail Solution", role: "Kotlin Android Developer", location: "القاهرة، مصر", mode: "دوام كامل · Hybrid", age: "LinkedIn مفتوح · منشور منذ 5 أيام · تحققت 5 أكتوبر", salary: "مخفي", match: "تطابق قوي", matchClass: "strong", why: "2+ سنوات Kotlin/Android، SDK، REST/JSON، secure auth، testing، deployment، وretail/POS integrations؛ مناسب جدًا لخبرة أسماء.", note: "الدور Hybrid في القاهرة؛ تاريخ الإغلاق المعلن 5 نوفمبر 2026، وbarcode/ERP خبرة إضافية مفيدة.", href: "https://eg.linkedin.com/jobs/view/kotlin-android-developer-at-delta-retail-solution-4473557188", coverLetter: `Dear Delta Retail Solution Hiring Team,\n\nI am applying for the Kotlin Android Developer position in Cairo. I have more than three years of production Android experience using Kotlin, Java, Android SDK, Jetpack Compose, XML/View Binding, MVVM, MVI, Clean Architecture, Coroutines, dependency injection, REST APIs, Firebase, Git, JUnit, and MockK.\n\nMy domain experience includes POS, invoices, payment integrations, secure data handling, performance optimization, and release management. This aligns closely with Delta Retail Solution’s Kotlin, REST/JSON, secure authentication, testing, deployment, and retail-device requirements.\n\nBest regards,\nAsmaa Atya` },
  { company: "Khazna", role: "Senior Android Developer", location: "القاهرة، مصر", mode: "دوام كامل · On-site/النموذج غير معلن", age: "LinkedIn مفتوح · منشور منذ أسبوع · تحققت 5 أكتوبر", salary: "مخفي", match: "فرصة ممكنة", matchClass: "stretch", why: "3+ سنوات Native Android، Kotlin، Dagger/Hilt، MVP/MVVM/MVI، Clean Architecture، CI/CD وunit tests؛ تطابق تقني ممتاز لكن المسمى Senior.", note: "Stretch بسبب مستوى Senior؛ الشركة FinTech مصرية والدور يركز على منتجات الدفع والـAndroid production.", href: "https://eg.linkedin.com/jobs/view/senior-android-developer-at-khazna-4440455368", coverLetter: `Dear Khazna Hiring Team,\n\nI am applying for the Senior Android Developer position in Cairo. I have more than three years of production Android experience using Kotlin, Java, Android SDK, Jetpack Compose, XML/View Binding, MVVM, MVI, Clean Architecture, Coroutines, dependency injection, REST APIs, Firebase, Git, JUnit, and MockK.\n\nMy experience includes POS, invoices, payment integrations, healthcare and government services, secure data handling, performance optimization, testing, and Google Play release management. These strengths align with Khazna’s Android, Kotlin, architecture, API, testing, and financial-services requirements.\n\nI understand the Senior title and am applying as an honest stretch candidate while highlighting my relevant 3+ years of production delivery.\n\nBest regards,\nAsmaa Atya` },
  { company: "Nile Bits, LLC.", role: "Android Developer · Payment SDK", location: "القاهرة، مصر", mode: "دوام كامل · Egypt team", age: "LinkedIn مفتوح · منشور منذ أسبوع · تحققت 5 أكتوبر", salary: "مزايا معلنة دون رقم", match: "فرصة ممكنة", matchClass: "stretch", why: "Kotlin Native Android، payment APIs، SDKs، testing، performance وrelease/versioning؛ المجال يطابق خبرة أسماء لكن الإعلان يطلب 4+ سنوات وSDK depth.", note: "Stretch لأن المطلوب 4+ سنوات وخبرة SDK/reusable libraries مفضلة؛ يوجد دعم إضافي لـFlutter/React Native.", href: "https://eg.linkedin.com/jobs/view/android-developer-at-nile-bits-llc-4470920246", coverLetter: `Dear Nile Bits Hiring Team,\n\nI am applying for the Android Developer position supporting the payment SDK ecosystem in Cairo. I have more than three years of production Android experience using Kotlin, Java, Android SDK, Jetpack Compose, XML/View Binding, MVVM, MVI, Clean Architecture, Coroutines, dependency injection, REST APIs, Firebase, Git, JUnit, and MockK.\n\nMy domain experience includes POS, invoices, payment integrations, secure data handling, performance optimization, testing, and release management. I am especially interested in the payment and merchant-integration focus of this role.\n\nI understand the posting asks for 4+ years and SDK depth, so I am applying as an honest stretch candidate.\n\nBest regards,\nAsmaa Atya` },
  { company: "Henkel", role: "Android Engineer", location: "القاهرة، مصر", mode: "دوام كامل · Egypt office", age: "LinkedIn مفتوح · منشور منذ 4 أيام · تحققت 5 أكتوبر", salary: "مخفي", match: "فرصة ممكنة", matchClass: "stretch", why: "3+ سنوات Android/Kotlin، Compose، clean architecture، performance، security، APIs وrelease؛ مناسب تقنيًا لكن React Native جزء أساسي من النطاق.", note: "Stretch لأن الدور mixed Android وReact Native؛ لا أذكر خبرة React Native غير مؤكدة في الخطاب.", href: "https://www.henkel.com/careers/find-your-job-apply/2211118-2211118", coverLetter: `Dear Henkel Hiring Team,\n\nI am applying for the Android Engineer position in Cairo. I have more than three years of production Android experience using Kotlin, Java, Android SDK, Jetpack Compose, XML/View Binding, MVVM, MVI, Clean Architecture, Coroutines, dependency injection, REST APIs, Firebase, Git, JUnit, and MockK.\n\nMy experience includes scalable mobile architecture, secure data handling, performance optimization, testing, Gradle and release workflows, and Google Play delivery. These strengths align closely with the Android/Kotlin, Compose, architecture, performance, security, and API requirements.\n\nI understand that React Native is also part of the role’s scope, so I am applying as an honest possible match with Android as my primary track.\n\nBest regards,\nAsmaa Atya` },
  { company: "Boutiqaat", role: "Senior Android Developer", location: "مصر الجديدة، القاهرة، مصر", mode: "دوام كامل · On-site/النموذج غير معلن", age: "LinkedIn مفتوح · منشور منذ 3 أسابيع · تحققت 5 أكتوبر", salary: "مخفي", match: "فرصة ممكنة", matchClass: "stretch", why: "Kotlin/Java، Compose/XML، MVVM، Clean Architecture، Hilt/Dagger، Coroutines/Flow، Retrofit، Firebase والاختبارات؛ قوي تقنيًا لكن 5+ سنوات وSenior.", note: "Stretch واضح بسبب شرط 5+ سنوات والقيادة؛ قدّميه فقط بعد الأدوار الأقرب للمستوى.", href: "https://eg.linkedin.com/jobs/view/senior-android-developer-at-boutiqaat-4463018513", coverLetter: `Dear Boutiqaat Hiring Team,\n\nI am applying for the Senior Android Developer position in Cairo. I have more than three years of production Android experience using Kotlin, Java, Android SDK, Jetpack Compose, XML/View Binding, MVVM, MVI, Clean Architecture, Coroutines, dependency injection, REST APIs, Firebase, Git, JUnit, and MockK.\n\nMy background includes multi-module architecture, POS and payment integrations, secure data handling, performance optimization, testing, Gradle workflows, and Google Play release management. These strengths align closely with Boutiqaat’s Kotlin, Compose/XML, architecture, performance, API, and testing stack.\n\nI understand the posting asks for 5+ years and Senior scope, so I am applying as an honest stretch candidate.\n\nBest regards,\nAsmaa Atya` },
] as const;

const rejected = [
  "أُزيلت الوظائف القديمة أو المغلقة أو التي لا تقدم مسارًا حيًا واضحًا؛ MIGRATIONIT وTAWANTECH لم يُحملا لأن المسارات الحالية قديمة أو تعود 410.",
  "استُبعدت Junior/Internship وReact Native-only وiOS-only والأدوار خارج مصر، كما لم أعتبر generic remote دليلًا على قبول العمل من مصر.",
  "بحثت LinkedIn Posts/content منفصلًا بترتيب Latest بالعربي والإنجليزي؛ النتائج القابلة للفتح لم تثبت عمرًا ظاهرًا خلال 72 ساعة مع إيميل أو WhatsApp، فالحصيلة الحقيقية لمحمد 0.",
] as const;

const androidRejected = [
  "أُزيلت Reference Agency لأن صفحة Twine الحالية كانت على وشك الإغلاق، وأُزيلت الوظائف التي لم تعد تعرض Apply أو التي ظهر فيها No longer accepting applications.",
  "استُبعدت Junior/Internship وFlutter-only وReact Native-only وiOS-only، وكذلك أدوار 5+ سنوات أو Team Lead إلا كـStretch واضح، ومنشورات DM/form-only.",
  "بحثت LinkedIn Posts/content منفصلًا بترتيب Latest وبمصطلحات Android وKotlin وCompose وWhatsApp؛ لم يثبت أي منشور مؤهل بعمر ظاهر خلال 72 ساعة، فالحصيلة الحقيقية لأسماء 0.",
] as const;

function JobCard({ job, index, android = false }: { job: (typeof flutterJobs)[number] | (typeof androidJobs)[number]; index: number; android?: boolean }) {
  const verification = job.age.replaceAll("تحققت 5 أكتوبر", "تحققت 6 أكتوبر").replace("منذ 5 أيام", "منذ 6 أيام");
  return <article className="jobCard"><div className="cardTop"><span className="rank">{String(index + 1).padStart(2, "0")}</span><span className={`match ${job.matchClass}`}>{job.match}</span></div><p className="company">{job.company}</p><h3>{job.role}</h3><div className="meta"><span>{job.location}</span><span>{job.mode}</span><span>{verification}</span></div><div className="salary"><span>الراتب</span><strong>{job.salary}</strong></div><p className="why"><b>ليه مناسبة:</b> {job.why}</p><p className="note"><b>خد بالك:</b> {job.note}</p><div className="actions"><CopyButton text={job.coverLetter} /><a href={job.href} target="_blank" rel="noreferrer">{android ? "افتح التقديم" : "افتح الوظيفة"} <span aria-hidden="true">↗</span></a></div></article>;
}

type DirectPost = { company: string; role: string; location: string; age: string; poster: string; posterRole: string; match: string; matchClass: string; summary: string; contact: string; note: string; href: string; whatsapp?: string; whatsappMessage?: string };
function DirectPostCards({ posts }: { posts: readonly DirectPost[] }) { return <div className="postGrid">{posts.map((post) => <article className="postCard" key={`${post.company}-${post.poster}`}><div className="cardTop"><span className="postSource">LinkedIn Post</span><span className={`match ${post.matchClass}`}>{post.match}</span></div><p className="company">{post.company}</p><h3>{post.role}</h3><div className="meta"><span>{post.location}</span><span>{post.age}</span></div><p className="poster"><b>صاحب المنشور:</b> {post.poster} · {post.posterRole}</p><p className="why"><b>ليه مناسبة:</b> {post.summary}</p><p className="postContact"><b>التواصل:</b> {post.contact}</p><p className="note"><b>خد بالك:</b> {post.note}</p><div className="postActions"><a href={post.href} target="_blank" rel="noreferrer">افتح نشاط صاحب الإعلان <span aria-hidden="true">↗</span></a>{post.whatsapp && post.whatsappMessage && <a className="whatsappButton" href={`https://wa.me/${post.whatsapp}?text=${encodeURIComponent(post.whatsappMessage)}`} target="_blank" rel="noreferrer">افتح WhatsApp <span aria-hidden="true">↗</span></a>}</div></article>)}</div>; }

function ReportTab({ android = false }: { android?: boolean }) {
  const jobs = android ? androidJobs : flutterJobs;
  const posts = android ? freshAndroidDirectPosts : freshFlutterDirectPosts;
  const applications = android ? freshAndroidEmailApplications : freshFlutterEmailApplications;
  const name = android ? "Asmaa Atya" : "Muhammad Essam";
  const rejectedItems = android ? androidRejected : rejected;
  const strong = jobs.filter((job) => job.matchClass === "strong").length;
  return <section className={`tabPanel ${android ? "androidPanel" : "flutterPanel"}`} aria-labelledby={android ? "android-tab" : "flutter-tab"}><div className="sectionHead"><div><p className="eyebrow">{android ? "Android Native · Asmaa Atya" : "Flutter · Muhammad Essam"}</p><h2>{strong} قوية{jobs.length - strong ? ` و${jobs.length - strong} ممكنة` : ""}</h2></div><p>{jobs.length} وظائف رسمية مفتوحة ومتحقق منها داخل مصر. LinkedIn Posts بترتيب Latest خلال آخر 72 ساعة: {posts.length} صالح؛ {posts.length < 5 ? `العدد الحقيقي أقل من 5 بعد الفلترة: ${posts.length} فقط.` : ""}</p></div><div className="jobGrid">{jobs.map((job, index) => <JobCard key={`${job.company}-${job.role}`} job={job} index={index} android={android} />)}</div><section className="linkedInSection" aria-label={`منشورات توظيف ${android ? "Android" : "Flutter"} على LinkedIn`}><div className="sectionHead"><div><p className="eyebrow">LinkedIn Posts · Email أو WhatsApp فقط</p><h2>تقديم مباشر لـ{ name } · {posts.length}</h2></div><p>الفلترة مصر فقط، والعمر الظاهر حتى 72 ساعة فقط. أي منشور بلا إيميل أو WhatsApp معلن لا يظهر هنا.</p></div><DirectPostCards posts={posts} /></section><EmailComposer candidate={name} applications={applications} /><div className="rejected" aria-label="الفرص المستبعدة"><p className="eyebrow">فلترة اليوم</p><h2>ليه فرص تانية ما دخلتش التقرير؟</h2><ul>{rejectedItems.map((item) => <li key={item}>{item}</li>)}</ul></div></section>;
}

export default function Home() { return <main><header className="hero"><nav aria-label="رأس التقرير"><span className="brand">فرص محمد وأسماء</span><span className="date">تقرير 6 أكتوبر 2026</span></nav><div className="heroCopy"><p className="eyebrow">Flutter وAndroid Native في مصر فقط</p><h1>اختار التخصص وشوف الفرص المناسبة لكل شخص.</h1><p className="intro">وظائف مصرية أو مؤكدة القبول من مصر، مع Cover Letters وقسم إرسال Gmail منفصل لكل مرشح.</p></div><div className="stats" aria-label="ملخص التقرير"><div><strong>2</strong><span>مسار وظيفي</span></div><div><strong>{flutterJobs.length}</strong><span>فرص Flutter</span></div><div><strong>{androidJobs.length}</strong><span>فرص Android</span></div></div></header><section className="criteria" aria-label="معايير البحث"><span>مصر فقط أو Remote من مصر</span><span>لا وظائف انتقال فقط</span><span>تقديم مفتوح ومسار واضح</span><span>Mid أو Senior كفرصة Stretch</span></section><section className="content"><fieldset className="candidateTabs"><legend className="srOnly">اختار تقرير الوظائف</legend><input className="tabInput" type="radio" name="candidate" id="flutter-tab" defaultChecked /><label className="tabLabel" htmlFor="flutter-tab"><span>Flutter — Muhammad Essam</span><small>محمد Essam</small></label><input className="tabInput" type="radio" name="candidate" id="android-tab" /><label className="tabLabel" htmlFor="android-tab"><span>Android Native — Asmaa Atya</span><small>أسماء Atya</small></label><ReportTab /><ReportTab android /></fieldset></section><footer><p>الترتيب مبني على قوة التطابق وحداثة الإعلان ووضوح الراتب ومسار التقديم.</p><p>آخر تحديث: 6 أكتوبر 2026 · القاهرة</p></footer></main>; }
