import CopyButton from "./CopyButton";
import EmailComposer from "./EmailComposer";
import { freshAndroidDirectPosts, freshAndroidEmailApplications, freshFlutterDirectPosts, freshFlutterEmailApplications } from "./fresh-data";

const flutterJobs = [
  { company: "AppFactory", role: "Flutter Developer", location: "نيو كايرو، مصر", mode: "دوام كامل · On-site", age: "صفحة الشركة الرسمية مفتوحة · تحققت 10 سبتمبر", salary: "تنافسي حسب الخبرة", match: "تطابق قوي", matchClass: "strong", why: "3–5 سنوات Flutter إنتاجي، Dart، state management، REST/WebSockets، الاختبارات وCI/CD؛ تطابق مباشر مع خبرة محمد.", note: "On-site في New Cairo؛ الراتب تنافسي وغير محدد رقميًا.", href: "https://www.appfactoryltd.com/flutter-developer.html", coverLetter: `Dear AppFactory Hiring Team,\n\nI am applying for the Flutter Developer position in New Cairo. I have more than three years of production experience building Flutter applications for Android, iOS, and Windows using Dart, BLoC/Cubit, GetX, Clean Architecture, REST APIs, Firebase, local storage, testing, GitHub Actions, and Fastlane.\n\nMy experience with production feature ownership, responsive UI, API and real-time integrations, performance improvements, automated tests, and mobile release workflows aligns closely with AppFactory’s requirements for Flutter, Dart, state management, REST/WebSockets, testing, CI/CD, and platform integrations.\n\nPortfolio: https://muhamaadessam.github.io/\n\nBest regards,\nMuhammad Essam` },
  { company: "Div Systems", role: "Flutter Mobile Application Developer", location: "القاهرة، مصر", mode: "دوام كامل · On-site", age: "صفحة الشركة الرسمية تعرض Apply Now · تحققت 10 سبتمبر", salary: "مخفي", match: "تطابق قوي", matchClass: "strong", why: "الدور يطلب 3+ سنوات Flutter وDart وdesign patterns وGit وREST؛ تطابق واضح مع خبرة محمد ومسار تقديم مباشر.", note: "القاهرة؛ الراتب غير معلن.", href: "https://portal.div-systems.com/jobs/detail/flutter-mobile-application-developer-33", coverLetter: `Dear Div Systems Hiring Team,\n\nI am applying for the Flutter Mobile Application Developer position in Cairo. I have more than three years of production experience building Flutter applications for Android, iOS, and Windows using Dart, BLoC/Cubit, GetX, Clean Architecture, REST APIs, Firebase, local storage, testing, GitHub Actions, and Fastlane.\n\nMy background in mobile architecture, API integration, testing, performance improvements, and release workflows matches the role’s Flutter, Dart, design-pattern, Git, and REST requirements.\n\nPortfolio: https://muhamaadessam.github.io/\n\nBest regards,\nMuhammad Essam` },
  { company: "Adree", role: "Flutter, Developer", location: "القاهرة، مصر", mode: "دوام كامل · On-site", age: "Workable يعرض Flutter Developer · تحققت 10 سبتمبر", salary: "مخفي", match: "تطابق قوي", matchClass: "strong", why: "3–6 سنوات Flutter، Dart، Bloc/Provider/Riverpod/GetX، REST/GraphQL، Firebase، التخزين المحلي والاختبارات؛ تطابق مباشر.", note: "القاهرة؛ الراتب غير معلن.", href: "https://apply.workable.com/adree/j/089D2DAF05/", coverLetter: `Dear Adree Hiring Team,\n\nI am applying for the Flutter Developer position in Cairo. I have more than three years of production experience building Flutter applications for Android, iOS, and Windows using Dart, BLoC/Cubit, GetX, Clean Architecture, REST APIs, Firebase, local storage, testing, GitHub Actions, and Fastlane.\n\nMy experience with modular architecture, API integrations, local persistence, performance improvements, debugging, and automated mobile releases aligns closely with Adree’s Flutter, state management, Firebase, storage, testing, and CI/CD requirements.\n\nPortfolio: https://muhamaadessam.github.io/\n\nBest regards,\nMuhammad Essam` },
  { company: "Al - Tadamun Microfinance Association", role: "Flutter Developer", location: "الدقي، الجيزة، مصر", mode: "دوام كامل · On-site", age: "Wuzzuf مفتوح · منشور 4 أيام · تحققت 11 سبتمبر", salary: "مخفي", match: "تطابق قوي", matchClass: "strong", why: "Flutter وDart وAndroid/iOS وREST وGit والاختبارات والنشر؛ الوصف يطابق خبرة محمد الإنتاجية ومسار Apply مفتوح.", note: "الدقي؛ سنوات الخبرة غير محددة والراتب مخفي، فراجعي المستوى والراتب قبل التقديم.", href: "https://wuzzuf.net/jobs/p/8lz2ytqqwmhg-flutter-developer-al-tadamun-microfinance-association-giza-egypt", coverLetter: `Dear Al - Tadamun Hiring Team,\n\nI am applying for the Flutter Developer position in Giza. I have more than three years of production experience building Flutter applications for Android, iOS, and Windows using Dart, BLoC/Cubit, GetX, Clean Architecture, REST APIs, Firebase, local storage, testing, GitHub Actions, and Fastlane.\n\nMy background in feature delivery, bug fixing, performance optimization, unit and integration testing, app-store deployment, and maintainable architecture aligns with your Flutter, Dart, REST, Git, testing, and release requirements.\n\nPortfolio: https://muhamaadessam.github.io/\n\nBest regards,\nMuhammad Essam` },
  { company: "MMB Logistics and Consulting Services", role: "Mobile Application Developer", location: "المعادي، القاهرة، مصر", mode: "دوام كامل · On-site", age: "Wuzzuf مفتوح · منشور 3 أيام · تحققت 11 سبتمبر", salary: "مخفي", match: "تطابق قوي", matchClass: "strong", why: "2–4 سنوات Flutter/Dart، BLoC/Cubit، Clean Architecture، MVVM، REST، SQLite/Hive، الاختبارات والنشر؛ تطابق مباشر مع خبرة محمد.", note: "المعادي؛ الراتب مخفي، لكن صفحة Wuzzuf تعرض Apply For Job ومسارًا واضحًا.", href: "https://wuzzuf.net/jobs/p/duzrl0ehefid-mobile-application-developer-mmb-logistics-and-consulting-services-cairo-egypt", coverLetter: `Dear MMB Logistics and Consulting Services Hiring Team,\n\nI am applying for the Mobile Application Developer position in Cairo. I have more than three years of production experience building Flutter applications for Android, iOS, and Windows using Dart, BLoC/Cubit, GetX, Clean Architecture, REST APIs, Firebase, local storage, testing, GitHub Actions, and Fastlane.\n\nMy experience with scalable architecture, state management, API integration, secure local storage, performance tuning, unit and integration testing, and Google Play/App Store releases aligns closely with your requirements.\n\nPortfolio: https://muhamaadessam.github.io/\n\nBest regards,\nMuhammad Essam` },
  { company: "Devop Technologies", role: "Flutter Mobile App Developer", location: "مدينة نصر، القاهرة، مصر", mode: "دوام كامل · On-site", age: "LinkedIn Jobs يعرض الدور · تحققت 11 سبتمبر", salary: "مخفي", match: "تطابق قوي", matchClass: "strong", why: "2+ سنوات مفضلة وFlutter/Dart وBLoC أو Provider أو Riverpod وREST وFirebase والأداء؛ الدور في القاهرة ومسار التقديم معلن.", note: "التقديم عبر نموذج Google؛ الراتب تنافسي وغير محدد رقميًا، والخبرة المطلوبة 1.5+ سنة.", href: "https://eg.linkedin.com/jobs/view/flutter-mobile-app-developer-%E2%80%93-full-time-at-devop-technologies-4253946114", coverLetter: `Dear Devop Technologies Hiring Team,\n\nI am applying for the Flutter Mobile App Developer position in Cairo. I have more than three years of production experience building Flutter applications for Android, iOS, and Windows using Dart, BLoC/Cubit, GetX, Clean Architecture, REST APIs, Firebase, local storage, testing, GitHub Actions, and Fastlane.\n\nMy experience with cross-platform feature delivery, reusable UI, REST and Firebase integrations, performance optimization, and production release workflows aligns with your Flutter, Dart, state management, API, and mobile performance requirements.\n\nPortfolio: https://muhamaadessam.github.io/\n\nBest regards,\nMuhammad Essam` },
] as const;

const androidJobs = [
  { company: "Vertex Technologies", role: "Middle Android Developer", location: "سمارت فيليج، الجيزة، مصر", mode: "دوام كامل · On-site", age: "صفحة الشركة الرسمية مفتوحة · تحققت 10 سبتمبر", salary: "بالدولار حسب الخبرة", match: "تطابق قوي", matchClass: "strong", why: "3+ سنوات Android تجاري مع Kotlin وJetpack Compose وDagger وMVVM وCoroutines وREST؛ مطابق مباشرة لخبرة أسماء.", note: "الدور في Smart Village؛ الراتب بالدولار حسب الصفحة وغير محدد رقميًا.", href: "https://vertextech-eg.com/vacancies/middle-android-developer", coverLetter: `Dear Vertex Technologies Hiring Team,\n\nI am applying for the Middle Android Developer position in Giza. I have more than three years of production Android experience using Kotlin, Java, Android SDK, Jetpack Compose, XML, MVVM, MVI, Clean Architecture, Coroutines, dependency injection, REST APIs, Firebase, Git, JUnit, and MockK.\n\nMy experience with multi-module architecture, SOLID principles, secure data handling, performance optimization, testing, and Google Play releases aligns closely with the role’s Kotlin, Compose, Dagger, Coroutines, MVVM, and REST requirements.\n\nI am based in Egypt and would welcome the opportunity to contribute to Vertex Technologies in Smart Village.\n\nBest regards,\nAsmaa Atya` },
  { company: "Reference Agency", role: "Android Developer (Kotlin)", location: "القاهرة، مصر", mode: "Part-time · Remote", age: "Twine مفتوح · يغلق خلال 11 يومًا · تحققت 9 سبتمبر", salary: "مخفي", match: "تطابق قوي", matchClass: "strong", why: "Kotlin وJetpack Compose وMVVM/MVI وCoroutines/Flow وRetrofit وRoom وHilt/Dagger وRTL؛ دور HealthTech مناسب جدًا لخبرة أسماء.", note: "Part-time وRemote من مصر؛ التقديم يتم من Twine.", href: "https://www.twine.net/projects/b9p620-reference-agency-android-developer-kotlin-app-developer-in-cairo-egypt-job", coverLetter: `Dear Reference Agency Hiring Team,\n\nI am applying for the Android Developer (Kotlin) position in Cairo. I have more than three years of production Android experience using Kotlin, Java, Android SDK, Jetpack Compose, XML, MVVM, MVI, Clean Architecture, Coroutines, dependency injection, REST APIs, Firebase, Git, JUnit, and MockK.\n\nThe role’s Compose, modern architecture, offline data, Arabic RTL, REST integration, testing, and Play Store requirements align closely with my background. My experience also includes secure data handling, performance optimization, and production release management.\n\nI would welcome the opportunity to contribute to the Arabic-first health product on the remote part-time arrangement.\n\nBest regards,\nAsmaa Atya` },
  { company: "Yassir", role: "Senior Mobile Android Engineer L6", location: "القاهرة أو الإسكندرية، مصر", mode: "دوام كامل · Hybrid", age: "Lever مفتوح · شرط 2+ سنوات · تحققت 9 سبتمبر", salary: "مزايا وتعويضات معلنة دون رقم", match: "تطابق قوي", matchClass: "strong", why: "الدور يطلب Android/Kotlin، REST، Git، push notifications و2+ سنوات، ومتاح في القاهرة والإسكندرية؛ المسمى أعلى من المستوى لكن الشرط مناسب.", note: "Senior/L6 title؛ قدّميها كتطابق قوي تقنيًا مع الانتباه لمستوى الدور.", href: "https://jobs.lever.co/Yassir/2d61362c-3737-4343-932e-88102265689d", coverLetter: `Dear Yassir Hiring Team,\n\nI am applying for the Senior Mobile Android Engineer L6 position in Egypt. I have more than three years of production Android experience using Kotlin, Java, Android SDK, Jetpack Compose, XML, MVVM, MVI, Clean Architecture, Coroutines, dependency injection, REST APIs, Firebase, Git, JUnit, and MockK.\n\nMy background includes multi-module architecture, POS and payment integrations, secure data handling, performance optimization, push notifications, testing, and Google Play release management. These strengths align with the role’s Android/Kotlin, REST, Git, reliability, and mobile delivery requirements.\n\nI am based in Egypt and would welcome a discussion about the Cairo or Alexandria hybrid arrangement.\n\nBest regards,\nAsmaa Atya` },
  { company: "Henkel", role: "Android Engineer", location: "القاهرة، مصر", mode: "دوام كامل · Egypt office", age: "صفحة Henkel الرسمية مفتوحة · تحققت 9 سبتمبر", salary: "مخفي", match: "فرصة ممكنة", matchClass: "stretch", why: "دور Android/Kotlin في القاهرة مع clean architecture والأداء والأمان؛ مناسب تقنيًا، لكن React Native جزء من النطاق أيضًا.", note: "Stretch لأن الدور مختلط Android وReact Native؛ الإيميل المعروض للاستفسارات وليس للتقديم.", href: "https://www.henkel.com/careers/find-your-job-apply/2211118-2211118", coverLetter: `Dear Henkel Hiring Team,\n\nI am applying for the Android Engineer position in Cairo. I have more than three years of production Android experience using Kotlin, Java, Android SDK, Jetpack Compose, XML, MVVM, MVI, Clean Architecture, Coroutines, dependency injection, REST APIs, Firebase, Git, JUnit, and MockK.\n\nMy experience includes scalable mobile architecture, secure data handling, performance optimization, testing, Gradle and release workflows, and Google Play delivery. These strengths align closely with the Android/Kotlin, clean architecture, performance, security, and collaboration requirements.\n\nI understand that React Native is also part of the role’s scope, so I am applying as an honest possible match with Android as my primary track.\n\nBest regards,\nAsmaa Atya` },
  { company: "BlackStone eIT", role: "Senior Android Developer", location: "القاهرة، مصر", mode: "دوام كامل · On-site", age: "Workable path verified by Otto · منشور 4 سبتمبر · تحققت 9 سبتمبر", salary: "مخفي", match: "فرصة ممكنة", matchClass: "stretch", why: "Android SDK وJava وREST وoffline storage وpush notifications والأداء؛ الدور مفتوح في القاهرة، لكن مستوى Senior ولا يظهر شرط خبرة مناسب بوضوح.", note: "التقديم عبر مسار Workable؛ Stretch لعدم وضوح سنوات الخبرة ولأن الدور Senior.", href: "https://ottoroles.com/job/blackstone-eit-2/senior-android-developer-workable:blackstone-eit-2:148B70F9D5", coverLetter: `Dear BlackStone eIT Hiring Team,\n\nI am applying for the Senior Android Developer position in Cairo. I have more than three years of production Android experience using Kotlin, Java, Android SDK, Jetpack Compose, XML, MVVM, MVI, Clean Architecture, Coroutines, dependency injection, REST APIs, Firebase, Git, JUnit, and MockK.\n\nMy background includes offline storage, push notifications, performance tuning, secure data handling, testing, and Google Play release management, which aligns with the role’s Android SDK, APIs, reliability, and optimization requirements.\n\nI understand the role is Senior, so I am applying as an honest stretch candidate and would welcome a discussion about the required experience level.\n\nBest regards,\nAsmaa Atya` },
  { company: "Luxoft", role: "Senior Android Developer", location: "القاهرة، مصر", mode: "دوام كامل · On-site", age: "صفحة Luxoft مفتوحة · منشور 3 سبتمبر · تحققت 9 سبتمبر", salary: "مخفي", match: "فرصة ممكنة", matchClass: "stretch", why: "Kotlin وAndroid SDK وJetpack Compose وCoroutines/Flow وDagger وRetrofit والاختبارات؛ قوي تقنيًا لكن Senior وقطاع IoT/automotive متخصص.", note: "Stretch بسبب المسمى Senior وMQTT/IoT المحتمل؛ الراتب غير معلن.", href: "https://career.luxoft.com/jobs/senior-android-developer-25119", coverLetter: `Dear Luxoft Hiring Team,\n\nI am applying for the Senior Android Developer position in Cairo. I have more than three years of production Android experience using Kotlin, Java, Android SDK, Jetpack Compose, XML, MVVM, MVI, Clean Architecture, Coroutines, dependency injection, REST APIs, Firebase, Git, JUnit, and MockK.\n\nMy experience includes multi-module architecture, performance optimization, secure data handling, API integration, unit testing, and Google Play release management. The role’s Android SDK, Kotlin, Compose, Coroutines/Flow, API, data-management, and testing requirements align closely with my background.\n\nI understand the role is Senior and may involve MQTT/IoT integration; I am applying as an honest stretch candidate.\n\nBest regards,\nAsmaa Atya` },
  { company: "Yassir", role: "Senior Mobile Android Engineer (KMM)", location: "القاهرة أو الإسكندرية، مصر", mode: "دوام كامل · Hybrid", age: "Lever مفتوح · شرط 4+ سنوات وKMM · تحققت 9 سبتمبر", salary: "مخفي", match: "فرصة ممكنة", matchClass: "stretch", why: "Android/Kotlin وREST وGit وتطبيقات إنتاجية مع فريق مصر؛ مناسب كـStretch لأن الدور يطلب 4+ سنوات وخبرة KMM.", note: "لا تقدّميها إلا كـStretch؛ خبرة KMM وشرط 4+ سنوات غير مؤكدة في ملف أسماء.", href: "https://jobs.lever.co/Yassir/bfc4ce54-e066-44c7-a0e4-4cc7e88e43cb", coverLetter: `Dear Yassir Hiring Team,\n\nI am applying for the Senior Mobile Android Engineer (KMM) position in Egypt. I have more than three years of production Android experience using Kotlin, Java, Android SDK, Jetpack Compose, XML, MVVM, MVI, Clean Architecture, Coroutines, dependency injection, REST APIs, Firebase, Git, JUnit, and MockK.\n\nMy experience includes multi-module architecture, POS and payment integrations, secure data handling, performance optimization, testing, push notifications, and Google Play release management. These strengths align with the role’s Android/Kotlin, REST, Git, and production mobile requirements.\n\nI understand the posting asks for 4+ years and KMM experience; I am applying as an honest stretch candidate and would welcome a discussion if the team is open to a strong 3+ year Android profile.\n\nBest regards,\nAsmaa Atya` },
] as const;

const rejected = [
  "استُبعدت الوظائف المغلقة أو التي لم يظهر لها مسار تقديم واضح اليوم، ومنها الأدوار القديمة وReact Native-only والوظائف خارج مصر.",
  "في LinkedIn Posts ظهرت منشورات Lumin Soft وMasarat كـCopied، وOpenToWork وJunior؛ لذلك لم أضفها كمنشورات تواصل مباشر.",
  "بحثت بترتيب Latest وبمصطلحات Flutter وMobile في مصر؛ لم يبقَ لمحمد منشور توظيف صالح خلال 72 ساعة بإيميل أو WhatsApp معلن.",
] as const;

const androidRejected = [
  "أُزيلت الأدوار القديمة أو المغلقة، ومنها الوظائف التي لم تعد تعرض Apply؛ لم أُبقِ أي مسار بلا تحقق اليوم.",
  "استُبعدت Junior/Internship وFlutter-only وReact Native-only وiOS-only، وكذلك منشور Senior Android المنسوخ أو رابط التقديم فقط.",
  "بحثت بترتيب Latest وبمصطلحات Android وKotlin في مصر؛ النتيجة المؤهلة لأسماء منشور واحد فقط خلال 72 ساعة بواتساب معلن، وهو ABG Egypt.",
] as const;

function JobCard({ job, index, android = false }: { job: (typeof flutterJobs)[number] | (typeof androidJobs)[number]; index: number; android?: boolean }) {
  const verification = job.age.replace(/تحققت (?:9|10) سبتمبر/g, "تحققت 11 سبتمبر");
  return <article className="jobCard"><div className="cardTop"><span className="rank">{String(index + 1).padStart(2, "0")}</span><span className={`match ${job.matchClass}`}>{job.match}</span></div><p className="company">{job.company}</p><h3>{job.role}</h3><div className="meta"><span>{job.location}</span><span>{job.mode}</span><span>{verification}</span></div><div className="salary"><span>الراتب</span><strong>{job.salary}</strong></div><p className="why"><b>ليه مناسبة:</b> {job.why}</p><p className="note"><b>خد بالك:</b> {job.note}</p><div className="actions"><CopyButton text={job.coverLetter} /><a href={job.href} target="_blank" rel="noreferrer">{android ? "افتح التقديم" : "افتح الوظيفة"} <span aria-hidden="true">↗</span></a></div></article>;
}

type DirectPost = { company: string; role: string; location: string; age: string; poster: string; posterRole: string; match: string; matchClass: string; summary: string; contact: string; note: string; href: string; whatsapp?: string; whatsappMessage?: string };
function DirectPostCards({ posts }: { posts: readonly DirectPost[] }) { return <div className="postGrid">{posts.map((post) => <article className="postCard" key={`${post.company}-${post.poster}`}><div className="cardTop"><span className="postSource">LinkedIn Post</span><span className={`match ${post.matchClass}`}>{post.match}</span></div><p className="company">{post.company}</p><h3>{post.role}</h3><div className="meta"><span>{post.location}</span><span>{post.age}</span></div><p className="poster"><b>صاحب المنشور:</b> {post.poster} · {post.posterRole}</p><p className="why"><b>ليه مناسبة:</b> {post.summary}</p><p className="postContact"><b>التواصل:</b> {post.contact}</p><p className="note"><b>خد بالك:</b> {post.note}</p><div className="postActions"><a href={post.href} target="_blank" rel="noreferrer">افتح نشاط صاحب الإعلان <span aria-hidden="true">↗</span></a>{post.whatsapp && post.whatsappMessage && <a className="whatsappButton" href={`https://wa.me/${post.whatsapp}?text=${encodeURIComponent(post.whatsappMessage)}`} target="_blank" rel="noreferrer">افتح WhatsApp <span aria-hidden="true">↗</span></a>}</div></article>)}</div>; }

function ReportTab({ android = false }: { android?: boolean }) {
  const jobs = android ? androidJobs : flutterJobs;
  const posts = android ? freshAndroidDirectPosts : freshFlutterDirectPosts;
  const applications = android ? freshAndroidEmailApplications : freshFlutterEmailApplications;
  const name = android ? "Asmaa Atya" : "Muhammad Essam";
  const rejectedItems = android ? androidRejected : rejected;
  const strong = jobs.filter((job) => job.matchClass === "strong").length;
  return <section className={`tabPanel ${android ? "androidPanel" : "flutterPanel"}`} aria-labelledby={android ? "android-tab" : "flutter-tab"}><div className="sectionHead"><div><p className="eyebrow">{android ? "Android Native · Asmaa Atya" : "Flutter · Muhammad Essam"}</p><h2>{strong} قوية{jobs.length - strong ? ` و${jobs.length - strong} ممكنة` : ""}</h2></div><p>{jobs.length} وظائف رسمية مفتوحة ومتحقق منها داخل مصر. LinkedIn Posts بترتيب Latest خلال آخر 72 ساعة: {posts.length} صالح؛ {posts.length < 5 ? `العدد الحقيقي أقل من 5 بعد الفلترة: ${posts.length} فقط.` : ""}</p></div><div className="jobGrid">{jobs.map((job, index) => <JobCard key={`${job.company}-${job.role}`} job={job} index={index} android={android} />)}</div><section className="linkedInSection" aria-label={`منشورات توظيف ${android ? "Android" : "Flutter"} على LinkedIn`}><div className="sectionHead"><div><p className="eyebrow">LinkedIn Posts · Email أو WhatsApp فقط</p><h2>تقديم مباشر لـ{ name } · {posts.length}</h2></div><p>الفلترة مصر فقط، والعمر الظاهر حتى 72 ساعة فقط. أي منشور بلا إيميل أو WhatsApp معلن لا يظهر هنا.</p></div><DirectPostCards posts={posts} /></section><EmailComposer candidate={name} applications={applications} /><div className="rejected" aria-label="الفرص المستبعدة"><p className="eyebrow">فلترة اليوم</p><h2>ليه فرص تانية ما دخلتش التقرير؟</h2><ul>{rejectedItems.map((item) => <li key={item}>{item}</li>)}</ul></div></section>;
}

export default function Home() { return <main><header className="hero"><nav aria-label="رأس التقرير"><span className="brand">فرص محمد وأسماء</span><span className="date">تقرير 11 سبتمبر 2026</span></nav><div className="heroCopy"><p className="eyebrow">Flutter وAndroid Native في مصر فقط</p><h1>اختار التخصص وشوف الفرص المناسبة لكل شخص.</h1><p className="intro">وظائف مصرية أو مؤكدة القبول من مصر، مع Cover Letters وقسم إرسال Gmail منفصل لكل مرشح.</p></div><div className="stats" aria-label="ملخص التقرير"><div><strong>2</strong><span>مسار وظيفي</span></div><div><strong>{flutterJobs.length}</strong><span>فرص Flutter</span></div><div><strong>{androidJobs.length}</strong><span>فرص Android</span></div></div></header><section className="criteria" aria-label="معايير البحث"><span>مصر فقط أو Remote من مصر</span><span>لا وظائف انتقال فقط</span><span>تقديم مفتوح ومسار واضح</span><span>Mid أو Senior كفرصة Stretch</span></section><section className="content"><fieldset className="candidateTabs"><legend className="srOnly">اختار تقرير الوظائف</legend><input className="tabInput" type="radio" name="candidate" id="flutter-tab" defaultChecked /><label className="tabLabel" htmlFor="flutter-tab"><span>Flutter — Muhammad Essam</span><small>محمد Essam</small></label><input className="tabInput" type="radio" name="candidate" id="android-tab" /><label className="tabLabel" htmlFor="android-tab"><span>Android Native — Asmaa Atya</span><small>أسماء Atya</small></label><ReportTab /><ReportTab android /></fieldset></section><footer><p>الترتيب مبني على قوة التطابق وحداثة الإعلان ووضوح الراتب ومسار التقديم.</p><p>آخر تحديث: 11 سبتمبر 2026 · القاهرة</p></footer></main>; }
