import CopyButton from "./CopyButton";
import EmailComposer from "./EmailComposer";
import { freshAndroidDirectPosts, freshAndroidEmailApplications, freshFlutterDirectPosts, freshFlutterEmailApplications } from "./fresh-data";

const flutterJobs = [
  {
    company: "Adree", role: "Flutter, Developer", location: "القاهرة، مصر", mode: "دوام كامل · Cairo", age: "LinkedIn يوضح Apply · تحققت 23 أغسطس", salary: "مخفي",
    match: "تطابق قوي", matchClass: "strong", why: "3–6 سنوات Flutter، Dart، Bloc/Provider/Riverpod/GetX، REST/GraphQL، Firebase، التخزين المحلي، الاختبارات وCI/CD؛ تطابق مباشر مع خبرة محمد الإنتاجية.",
    note: "الوظيفة في القاهرة؛ الراتب غير معلن.", href: "https://apply.workable.com/adree/j/089D2DAF05/",
    coverLetter: `Dear Adree Hiring Team,\n\nI am applying for the Flutter, Developer position in Cairo. I have more than three years of production experience building Flutter applications for Android, iOS, and Windows using Dart, BLoC/Cubit, GetX, Clean Architecture, REST APIs, Firebase, local storage, testing, GitHub Actions, and Fastlane.\n\nMy experience includes production feature ownership, modular architecture, API integrations, local persistence, performance improvements, debugging, and automated mobile releases. Adree’s requirements around Flutter architecture, state management, APIs, Firebase, local storage, testing, and CI/CD align closely with my background.\n\nI am based in Egypt and would welcome the opportunity to contribute to Adree’s mobile products.\n\nPortfolio: https://muhamaadessam.github.io/\n\nBest regards,\nMuhammad Essam`,
  },
  {
    company: "Nawy Real Estate", role: "Senior Flutter Developer", location: "المعادي، القاهرة، مصر", mode: "دوام كامل · On-site", age: "LinkedIn يوضح Actively Hiring · تحققت 23 أغسطس", salary: "مخفي",
    match: "تطابق قوي", matchClass: "strong", why: "الدور يطلب 3–5 سنوات Flutter، Android/iOS، APIs، SQL/NoSQL، automated testing وGit؛ تطابق جيد مع خبرة محمد الإنتاجية عبر المنصات.",
    note: "المسمى Senior لكن شرط الخبرة 3–5 سنوات؛ الراتب غير معلن.", href: "https://eg.linkedin.com/jobs/view/senior-flutter-developer-at-nawy-4437781538",
    coverLetter: `Dear Nawy Hiring Team,\n\nI am applying for the Senior Flutter Developer position in Maadi. I have more than three years of production experience building Flutter applications for Android, iOS, and Windows using Dart, BLoC/Cubit, GetX, Clean Architecture, REST APIs, Firebase, local storage, testing, GitHub Actions, and Fastlane.\n\nMy background includes modular architecture, API integrations, local persistence, performance improvements, unit testing, and reliable mobile releases. Nawy’s requirements around Flutter, Android/iOS delivery, APIs, data storage, testing, and Git align closely with my production experience.\n\nI am based in Egypt and would welcome the opportunity to contribute to Nawy’s mobile products.\n\nPortfolio: https://muhamaadessam.github.io/\n\nBest regards,\nMuhammad Essam`,
  },
  {
    company: "TAWANTECH", role: "Senior Flutter Developer offshore", location: "القاهرة، مصر", mode: "دوام كامل · On-site", age: "Workable منشور منذ 7 أيام · تحققت 23 أغسطس", salary: "مخفي",
    match: "فرصة ممكنة", matchClass: "stretch", why: "الدور في القاهرة ويطلب 3+ سنوات Flutter وDart وBLoC/Riverpod/Provider/GetX وREST وFirebase وCI/CD؛ قوي تقنيًا لكن المسمى Senior وشرط 5+ سنوات إجمالي Stretch صريح.",
    note: "قدّمها كفرصة Stretch فقط؛ يطلب 5+ سنوات إجمالي والحضور On-site في القاهرة.", href: "https://jobs.workable.com/view/nsGabGUXdxbV21nTqgEpTm/senior-flutter-developer-offshore-in-cairo-at-tawantech",
    coverLetter: `Dear TAWANTECH Hiring Team,\n\nI am applying for the Senior Flutter Developer position in Cairo. I have more than three years of production experience building Flutter applications for Android, iOS, and Windows using Dart, BLoC/Cubit, GetX, Clean Architecture, REST APIs, Firebase, local storage, testing, GitHub Actions, and Fastlane.\n\nI have owned production features from architecture through release, integrated backend and third-party services, improved performance, and supported reliable mobile delivery. The role’s Flutter, API, Firebase, architecture, CI/CD, and deployment requirements align closely with my hands-on experience.\n\nI am based in Egypt and would welcome a discussion about the Senior scope and the Cairo on-site arrangement.\n\nPortfolio: https://muhamaadessam.github.io/\n\nBest regards,\nMuhammad Essam`,
  },
  {
    company: "Envision Employment Solutions", role: "Senior Mobile Developer (Flutter)", location: "نيو كايرو، القاهرة، مصر", mode: "دوام كامل · Hybrid", age: "Workable مفتوح · تحققت 23 أغسطس", salary: "مخفي",
    match: "فرصة ممكنة", matchClass: "stretch", why: "تقديم مفتوح لدور Flutter في القاهرة مع REST، architecture، state management، testing وCI/CD؛ مناسب تقنيًا، لكن شرط 6+ سنوات وقيادة/mentoring أعلى من خبرة محمد المؤكدة.",
    note: "Senior واضح وشرط 6+ سنوات؛ يُعامل كـStretch فقط قبل استثمار وقت كبير.", href: "https://apply.workable.com/envisiones/j/4113BA49A5",
    coverLetter: `Dear Envision Employment Solutions Hiring Team,\n\nI am applying for the Senior Mobile Developer (Flutter) position in Cairo. I have more than three years of production experience building Flutter applications for Android, iOS, and Windows using Dart, BLoC/Cubit, GetX, Clean Architecture, REST APIs, Firebase, local storage, testing, GitHub Actions, and Fastlane.\n\nMy background includes production feature ownership, modular architecture, API integrations, performance improvements, testing, and automated mobile releases. The role’s focus on Flutter, architecture, state management, APIs, quality, and CI/CD aligns closely with my experience.\n\nI understand the posting asks for 6+ years and senior-level technical leadership; I am applying as an honest stretch candidate and would welcome a discussion if the team is open to a strong 3+ year production profile.\n\nPortfolio: https://muhamaadessam.github.io/\n\nBest regards,\nMuhammad Essam`,
  },
  {
    company: "BlueCloud Technologies", role: "Senior Mobile Developer", location: "القاهرة، مصر", mode: "دوام كامل · On-site", age: "Workable مفتوح · تحققت 23 أغسطس", salary: "مخفي",
    match: "فرصة ممكنة", matchClass: "stretch", why: "الدور في القاهرة ويطلب 3–5 سنوات مع Flutter وREST/GraphQL وBLoC/Provider وFirebase وFastlane؛ مناسب جزئيًا، لكن React Native جزء أساسي من النطاق والمسمى Senior.",
    note: "قدّمه فقط إذا كان الفريق يقبل Flutter كمسار أساسي؛ الراتب غير معلن.", href: "https://apply.workable.com/bluecloud-technologies/j/63F5874D1A/",
    coverLetter: `Dear BlueCloud Technologies Hiring Team,\n\nI am applying for the Senior Mobile Developer position in Cairo, with Flutter as my primary track. I have more than three years of production experience building Flutter applications for Android, iOS, and Windows using Dart, BLoC/Cubit, GetX, Clean Architecture, REST APIs, Firebase, local storage, testing, GitHub Actions, and Fastlane.\n\nMy background includes modular architecture, API integrations, push notifications, performance improvements, testing, and mobile release automation. The role’s Flutter, API, state management, Firebase, CI/CD, and app-store delivery requirements align closely with my experience.\n\nI would welcome a discussion about the Flutter scope within the mixed mobile team and the Cairo on-site arrangement.\n\nPortfolio: https://muhamaadessam.github.io/\n\nBest regards,\nMuhammad Essam`,
  },
] as const;

const androidJobs = [
  {
    company: "onebank", role: "Mobile Application Developer (Multiple Levels)", location: "المعادي، القاهرة، مصر", mode: "دوام كامل · Android Native", age: "LinkedIn يوضح التقدم · تحققت 23 أغسطس", salary: "مخفي",
    match: "تطابق قوي", matchClass: "strong", why: "onebank بنك رقمي مصري ويبحث عن مستويات متعددة في Android مع اهتمام بالصيانة والأمان وتجربة المستخدم؛ مناسب جدًا لخبرة أسماء في Kotlin والمدفوعات والأمان.",
    note: "الإعلان يجمع Android وiOS؛ اختاري مسار Android فقط عند التقديم.", href: "https://eg.linkedin.com/jobs/view/mobile-application-developer-multiple-levels-at-onebank-4445618680",
    coverLetter: `Dear onebank Hiring Team,\n\nI am applying for the Mobile Application Developer position on the Android track. I have more than three years of production Android experience using Kotlin, Java, Android SDK, Jetpack Compose, XML, MVVM, MVI, Clean Architecture, Coroutines, dependency injection, REST APIs, Firebase, Git, JUnit, and MockK.\n\nMy background includes POS, invoices, payment integrations, secure data handling, multi-module architecture, performance optimization, Google Play releases, and an Egypt Ministry of Justice application serving more than one million users. onebank’s focus on secure digital banking in Egypt aligns closely with my Android and payments experience.\n\nI am based in Egypt and would welcome the opportunity to discuss the Android scope.\n\nBest regards,\nAsmaa Atya`,
  },
  {
    company: "Luxoft", role: "Regular/Senior Android Developer", location: "القاهرة، مصر", mode: "دوام كامل · Android", age: "صفحة Luxoft الرسمية مفتوحة · تحققت 23 أغسطس", salary: "مخفي",
    match: "فرصة ممكنة", matchClass: "stretch", why: "الدور في القاهرة ويطلب Android SDK، Kotlin، Compose، Coroutines/Flow، MVVM، Dagger، Retrofit والاختبارات؛ التطابق التقني قوي لكن المسمى Senior.",
    note: "ناقشي المستوى المناسب؛ الصفحة الرسمية تعرض Senior والراتب غير معلن.", href: "https://career.luxoft.com/jobs/regularsenior-android-developer-25119",
    coverLetter: `Dear Luxoft Hiring Team,\n\nI am applying for the Regular/Senior Android Developer position in Cairo. I have more than three years of production Android experience using Kotlin, Java, Android SDK, Jetpack Compose, XML, MVVM, MVI, Clean Architecture, Coroutines, dependency injection, REST APIs, Firebase, Git, JUnit, and MockK.\n\nMy background includes POS, invoices, payment integrations, secure data handling, multi-module architecture, performance optimization, unit testing, and Google Play release management. The role’s requirements around Android SDK, Kotlin, Compose, Coroutines/Flow, MVVM, Dagger, Retrofit, API integration, and testing align closely with my experience.\n\nI am based in Egypt and would welcome the opportunity to contribute to the Cairo team.\n\nBest regards,\nAsmaa Atya`,
  },
  {
    company: "Egyptian Banks Company", role: "Senior Engineer, Mobile Software Development (Android)", location: "القاهرة الجديدة، مصر", mode: "دوام كامل · Android Native", age: "LinkedIn يوضح التقدم · تحققت 23 أغسطس", salary: "مخفي",
    match: "تطابق قوي", matchClass: "strong", why: "الدور يطلب تقريبًا 3+ سنوات مع Kotlin/Java، Android SDK، Compose lifecycle، MVVM/MVI، Retrofit، Room، Coroutines/Flow، الاختبارات وCI/CD؛ تطابق مباشر مع خبرة أسماء.",
    note: "دور Senior في بنك مصري؛ الراتب غير معلن.", href: "https://eg.linkedin.com/jobs/view/senior-engineer-mobile-software-development-android-at-egyptian-banks-company-4454740534",
    coverLetter: `Dear Egyptian Banks Company Hiring Team,\n\nI am applying for the Senior Engineer, Mobile Software Development (Android) position in New Cairo. I have more than three years of production Android experience using Kotlin, Java, Android SDK, Jetpack Compose, XML, MVVM, MVI, Clean Architecture, Coroutines, dependency injection, REST APIs, Firebase, Git, JUnit, and MockK.\n\nMy background includes POS, invoices, payment integrations, secure data handling, multi-module architecture, performance optimization, unit testing, CI/CD, and Google Play release management. The role’s Kotlin/Java, Android SDK, MVVM/MVI, Retrofit, local storage, Coroutines/Flow, security, testing, and release requirements align closely with my experience.\n\nI am based in Egypt and would welcome the opportunity to contribute to Egyptian Banks Company’s mobile products.\n\nBest regards,\nAsmaa Atya`,
  },
  {
    company: "TrianglZ", role: "Mid-Senior Android Engineer", location: "الإسكندرية، مصر", mode: "دوام كامل · Hybrid", age: "صفحة التقديم محدثة منذ أسبوع · تحققت 23 أغسطس", salary: "مخفي",
    match: "تطابق قوي", matchClass: "strong", why: "الدور يطلب 3 سنوات مع Kotlin، Jetpack Compose، Coroutines/Flow، Dagger/Hilt، MVVM/MVI، Clean Architecture، Git وPush APIs؛ تطابق مباشر مع خبرة أسماء.",
    note: "العمل Hybrid في الإسكندرية؛ الراتب غير معلن.", href: "https://join.com/companies/trianglz/16569950-mid-senior-android-engineer",
    coverLetter: `Dear TrianglZ Hiring Team,\n\nI am applying for the Mid-Senior Android Engineer position in Alexandria. I have more than three years of production Android experience using Kotlin, Java, Android SDK, Jetpack Compose, XML, MVVM, MVI, Clean Architecture, Coroutines, dependency injection, REST APIs, Firebase, Git, JUnit, and MockK.\n\nMy background includes multi-module architecture, POS and payment integrations, secure data handling, performance optimization, testing, Google Play releases, and production delivery. The role’s Kotlin, Compose, Coroutines/Flow, DI, MVVM/MVI, Clean Architecture, Git, and push-notification requirements align closely with my experience.\n\nI am based in Egypt and would welcome a discussion about the Alexandria hybrid arrangement.\n\nBest regards,\nAsmaa Atya`,
  },
  {
    company: "geidea", role: "Senior Android Developer", location: "القاهرة، مصر", mode: "دوام كامل · Android/KMM", age: "LinkedIn يوضح التقدم · تحققت 23 أغسطس", salary: "مخفي",
    match: "فرصة ممكنة", matchClass: "stretch", why: "الدور يطابق Kotlin/Android وREST وGit وتطوير تطبيقات فعلية، لكن يطلب 4+ سنوات وخبرة KMM؛ مناسب كـStretch فقط.",
    note: "يطلب 4–5 سنوات وخبرة KMM؛ قدّميها كـStretch فقط والراتب غير معلن.", href: "https://eg.linkedin.com/jobs/view/senior-android-developer-at-geidea-4456302158",
    coverLetter: `Dear geidea Hiring Team,\n\nI am applying for the Senior Android Developer position in Cairo. I have more than three years of production Android experience using Kotlin, Java, Android SDK, Jetpack Compose, XML, MVVM, MVI, Clean Architecture, Coroutines, dependency injection, REST APIs, Firebase, Git, JUnit, and MockK.\n\nMy background includes POS, invoices, payment integrations, secure data handling, multi-module architecture, performance optimization, unit testing, and Google Play release management. geidea’s fintech focus and the role’s Android, Compose, modular architecture, APIs, testing, security, and delivery requirements align closely with my experience.\n\nI understand the posting asks for 4–5 years and practical KMM experience; I am applying as an honest stretch candidate and would welcome a discussion if the team is open to a strong 3+ year Android profile.\n\nBest regards,\nAsmaa Atya`,
  },
] as const;

const rejected = [
  "أُزيلت الوظائف القديمة أو التي لم تعد تفتح مسار تقديم واضحًا؛ لم أُبقِ أي بطاقة من تحديث سابق بلا إعادة تحقق اليوم.",
  "TAWANTECH وEnvision موجودتان كـStretch بسبب 5+ و6+ سنوات؛ BlueCloud يطلب React Native بجانب Flutter.",
  "تعذّر الوصول إلى LinkedIn Posts من جلسة المتصفح اليوم، والنتائج العامة لا تثبت عمرًا داخل 72 ساعة؛ لذلك لم أضع أي إيميل/WhatsApp.",
] as const;

const androidRejected = [
  "استُبعدت Henkel لأن LinkedIn يوضح أن التقديم لم يعد مقبولًا، واستُبعدت Yassir من القائمة الرئيسية لأن شرط 4+ سنوات وKMM أعلى من الأولوية.",
  "استُبعدت الأدوار Junior/Internship وFlutter-only وReact Native-only وiOS-only.",
  "تعذّر الوصول إلى LinkedIn Posts من جلسة المتصفح اليوم، والنتائج العامة لا تثبت عمرًا داخل 72 ساعة؛ لذلك لم أضع أي إيميل/WhatsApp.",
] as const;

function JobCard({ job, index, android = false }: { job: (typeof flutterJobs)[number] | (typeof androidJobs)[number]; index: number; android?: boolean }) {
  return <article className="jobCard"><div className="cardTop"><span className="rank">{String(index + 1).padStart(2, "0")}</span><span className={`match ${job.matchClass}`}>{job.match}</span></div><p className="company">{job.company}</p><h3>{job.role}</h3><div className="meta"><span>{job.location}</span><span>{job.mode}</span><span>{job.age}</span></div><div className="salary"><span>الراتب</span><strong>{job.salary}</strong></div><p className="why"><b>ليه مناسبة:</b> {job.why}</p><p className="note"><b>خد بالك:</b> {job.note}</p><div className="actions"><CopyButton text={job.coverLetter} /><a href={job.href} target="_blank" rel="noreferrer">{android ? "افتح التقديم" : "افتح الوظيفة"} <span aria-hidden="true">↗</span></a></div></article>;
}

type DirectPost = { company: string; role: string; location: string; age: string; poster: string; posterRole: string; match: string; matchClass: string; summary: string; contact: string; note: string; href: string; whatsapp?: string; whatsappMessage?: string };

function DirectPostCards({ posts }: { posts: readonly DirectPost[] }) {
  return <div className="postGrid">{posts.map((post) => <article className="postCard" key={`${post.company}-${post.poster}`}><div className="cardTop"><span className="postSource">LinkedIn Post</span><span className={`match ${post.matchClass}`}>{post.match}</span></div><p className="company">{post.company}</p><h3>{post.role}</h3><div className="meta"><span>{post.location}</span><span>{post.age}</span></div><p className="poster"><b>صاحب المنشور:</b> {post.poster} · {post.posterRole}</p><p className="why"><b>ليه مناسبة:</b> {post.summary}</p><p className="postContact"><b>التواصل:</b> {post.contact}</p><p className="note"><b>خد بالك:</b> {post.note}</p><div className="postActions"><a href={post.href} target="_blank" rel="noreferrer">افتح نشاط صاحب الإعلان <span aria-hidden="true">↗</span></a>{post.whatsapp && post.whatsappMessage && <a className="whatsappButton" href={`https://wa.me/${post.whatsapp}?text=${encodeURIComponent(post.whatsappMessage)}`} target="_blank" rel="noreferrer">افتح WhatsApp <span aria-hidden="true">↗</span></a>}</div></article>)}</div>;
}

function ReportTab({ android = false }: { android?: boolean }) {
  const jobs = android ? androidJobs : flutterJobs;
  const posts = android ? freshAndroidDirectPosts : freshFlutterDirectPosts;
  const applications = android ? freshAndroidEmailApplications : freshFlutterEmailApplications;
  const name = android ? "Asmaa Atya" : "Muhammad Essam";
  const rejectedItems = android ? androidRejected : rejected;
  const strong = jobs.filter((job) => job.matchClass === "strong").length;
  return <section className="tabPanel" aria-labelledby={android ? "android-tab" : "flutter-tab"}><div className="sectionHead"><div><p className="eyebrow">{android ? "Android Native · Asmaa Atya" : "Flutter · Muhammad Essam"}</p><h2>{strong} قوية{jobs.length - strong ? ` و${jobs.length - strong} ممكنة` : ""}</h2></div><p>{jobs.length} وظائف رسمية مفتوحة ومتحقق منها داخل مصر. LinkedIn Posts بترتيب Latest خلال آخر 72 ساعة: {posts.length} صالح؛ لا توجد بطاقة مباشرة أو مسودة بريد لأن العمر ووسيلة التواصل لم يُثبتَا اليوم.</p></div><div className="jobGrid">{jobs.map((job, index) => <JobCard key={`${job.company}-${job.role}`} job={job} index={index} android={android} />)}</div><section className="linkedInSection" aria-label={`منشورات توظيف ${android ? "Android" : "Flutter"} على LinkedIn`}><div className="sectionHead"><div><p className="eyebrow">LinkedIn Posts · Email أو WhatsApp فقط</p><h2>تقديم مباشر لـ{ name } · {posts.length}</h2></div><p>الفلترة مصر فقط، والسن حتى 72 ساعة فقط. أي منشور بلا إيميل أو WhatsApp معلن لا يظهر هنا.</p></div><DirectPostCards posts={posts} /></section><EmailComposer candidate={name} applications={applications} /><div className="rejected" aria-label="الفرص المستبعدة"><p className="eyebrow">فلترة اليوم</p><h2>ليه فرص تانية ما دخلتش التقرير؟</h2><ul>{rejectedItems.map((item) => <li key={item}>{item}</li>)}</ul></div></section>;
}

export default function Home() {
  return <main><header className="hero"><nav aria-label="رأس التقرير"><span className="brand">فرص محمد وأسماء</span><span className="date">تقرير 23 أغسطس 2026</span></nav><div className="heroCopy"><p className="eyebrow">Flutter وAndroid Native في مصر فقط</p><h1>اختار التخصص وشوف الفرص المناسبة لكل شخص.</h1><p className="intro">وظائف مصرية أو مؤكدة القبول من مصر، مع Cover Letters وقسم إرسال Gmail منفصل لكل مرشح.</p></div><div className="stats" aria-label="ملخص التقرير"><div><strong>2</strong><span>مسار وظيفي</span></div><div><strong>{flutterJobs.length}</strong><span>فرص Flutter</span></div><div><strong>{androidJobs.length}</strong><span>فرص Android</span></div></div></header><section className="criteria" aria-label="معايير البحث"><span>مصر فقط أو قبول مصر مؤكد</span><span>لا وظائف انتقال فقط</span><span>تقديم مفتوح ومسار واضح</span><span>Mid أو Senior كفرصة Stretch</span></section><section className="content"><fieldset className="candidateTabs"><legend className="srOnly">اختار تقرير الوظائف</legend><input className="tabInput" type="radio" name="candidate" id="flutter-tab" defaultChecked /><label className="tabLabel" htmlFor="flutter-tab"><span>Flutter — Muhammad Essam</span><small>محمد Essam</small></label><input className="tabInput" type="radio" name="candidate" id="android-tab" /><label className="tabLabel" htmlFor="android-tab"><span>Android Native — Asmaa Atya</span><small>أسماء Atya</small></label><ReportTab /><ReportTab android /></fieldset></section><footer><p>الترتيب مبني على قوة التطابق وحداثة الإعلان ووضوح الراتب ومسار التقديم.</p><p>آخر تحديث: 23 أغسطس 2026 · القاهرة</p></footer></main>;
}
